# -*- coding: utf-8 -*-
"""Qr code in python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lRf18MNyV1byleA-ct5C1raFu9k1qTVH
"""

!pip install qrcode

import qrcode

img = qrcode.make('https://github.com/ErkinovTolibjonn')

image = img.save('GitHubUrl.png')

image